export const TEXT_ES:{[key: string]: string } = {
  primerTitulo: '¡NOS CASAMOS!',
  tNombres: 'Lucia y Junnior',
  traduccion: 'Traducir a Inglés',
  splashClick: 'Haz clic aqu\u00ed',
  envelopeFor: 'Para',
  seatReservedSingular: 'asiento reservado',
  seatReservedPlural: 'asientos reservados',
  pCancion: 'Tu navegador no soporta el elemento de audio.',
  subTitulo: 'You are invited!',
  mensajeBienvenida1: 'Hay momentos en la vida que se vuelven extraordinarios cuando se comparten con quienes amamos.',
  mensajeBienvenida2: 'Por eso, te invitamos a celebrar con nosotros el inicio de este hermoso viaje.',
  mensajeBienvenida3: 'Tu presencia en el día más importante de nuestras vidas será invaluable para nosotros.',
  soloFaltan: 'FALTAN',
  counterDias: 'DÍAS',
  counterHoras: 'HORAS',
  counterMinutos: 'MINUTOS',
  counterSeg: 'SEGUNDOS',
  // NOMBRE DE PADRES
  tituloInicialPadres: 'Con la bendición de Dios',
  subTituloInicialPadres: 'y nuestros padres',
  nomPadresNovia: 'Padres de la novia',
  nomPadresNovio: 'Padres del novio',
  // FECHA Y BODA
  textFechaBoda: 'Nuestra boda será el sábado:',
  fechaBoda: '08 | Marzo | 2025',
  // GUARDAR LA FECHA
  guardaFecha: 'GUARDA LA FECHA',
  // CEREMONIA Y RECEPCIÓN
  tituloCeremonia: 'CEREMONIA Y RECEPCIÓN',
  direccionCeremonia: 'Iglesia Nuestra Señora del Carmen, Piura, Perú',
  horaCeremonia: 'Hora: 3:30 Hrs.',
  ubicacion: 'Ver Ubicación',
  tituloRecepcion: 'RECEPCIÓN',
  direccionRecepcion: 'Centro de eventos El Remanso, Los Ejidos, Piura, Perú',
  horaRecepcion: 'Hora: 4:30 Hrs.',
  //ITINERARIO
  tituloItinerario1: 'Itinerario',
  subttuloItinerario: 'de boda',
  itiCeremonia: 'Ceremonia',
  itiCeremoniaHora: '15:00 Hrs. - 23:00 Hrs.',
  itiRecepcion: 'Recepción',
  itiRecepcionHora: '19:00 Hrs.',
  itiBaile: 'Primer Baile',
  itiBaileHora: '06:30 Hrs.',
  itiComida: 'Comida',
  itiComidaHora: '20:30 Hrs.',
  itiPastel: 'Pastel',
  itiPastelHora: '07:00 Hrs.',
  itiFiesta: 'Fiesta',
  itiFiestaHora: '22:00 Hrs.',
  itiDespedida: 'Despedida',
  itiDespedidaHora: '11:00 Hrs.',
  // VESTIMENTA O DRESS CODE
  tituloVestimenta: 'VESTIMENTA',
  textoVestimentaUno: 'Long gown cocktail dress',
  textoVestimentaDos: '',
  // NUESTROS MOMENTOS
  tituloMomentos: 'Nuestros momentos',
  textoMomentos: 'Ayuda a que nuestros recuerdos de este día especial crezcan. Usa el código QR para compartir tus momentos y ser parte de nuestra historia',
  // REGALOS
  tituloRegalo: 'Regalos',
  textoRegaloUno: 'Tu presencia es nuestro mejor regalo, pero si deseas tener un detalle con nosotros, haz clic aquí para ver las opciones',
  subtituloRegalo: 'Lluvia de sobres',
  textoRegaloDos: 'Los obsequios en efectivo siempre son bienvenidos, pero nunca obligatorios. Todo lo que te pedimos es que estés aquí con nosotros.',
  // NO NIÑOS
  tituloKids: 'Sólo para adultos',
  textoKids: ' Adoramos a los pequeños, sin embargo esta celebración está destinada solo para adultos.¡Agradecemos su comprensión! <br><br> NO NIÑOS',
  // PASES
  tituloPases: 'PASES',
  textoPasesUno: 'Están reservados para ti',
  textoPasesDos: '2 asientos en tu honor.',
  //CONFIRMACIÓN DE ASISTENCIA
  tituloConfirmacion: 'Confirma tu asistencia',
  textoConfirmacionUno: 'Por favor, confirma tu asistencia lo antes posible.',
  textoConfirmacionDos: '',
  textoConfirmacionTres: 'Contacta a los novios.',
  buttonConfirmacion: 'Contacto Diego',
  buttonForms: 'Confirmar',
  // CONFIRMACION
  mensaje_confirmado: 'CONFIRMACIÓN DE ASISTENCIA',
  yaConfirAsistencia: '¡Ya has confirmado tu asistencia!',
  mensajeBienvenidaConfirm: 'Esperamos contar con tu presencia. Por favor, confirma tu asistencia antes del ',
  cantidadAsistentes: 'El número de asientos reservados para ti es:',
  alertCantidadAsis: 'Cantidad de asistentes',
  alertaPuedesConfirmarHasta: 'Puedes confirmar hasta',
  alertaMinimoConfirmaciones: 'Debes ingresar al menos un invitado.',
  invitNoEspecificado: 'Nos hemos dado cuenta de que no se especificaron los nombres de tus acompañantes. Te agradeceríamos mucho si pudieras proporcionarnos esta información para poder llevar un mejor control.',
  mesaAsignada: 'Tu lugar está en la mesa número:',
  NombreInvitadoInput: 'Nombre invitado',
  botonConfirmacion: 'Confirmar',
  totalInvitadosConfirmado: 'Asientos reservados:',
  mesa: 'Número de mesa:',
  despedidaEsperamosVerte: '¡Te esperamos!',
  acompañantesAgregados: 'Acompañantes agregados:',
  txtNoAsistencia: 'Lamentamos que no puedas acompañarnos. ¡Esperamos verte muy pronto!',
  debesIngresarInvitados: 'Debes ingresar al menos un invitado',
  puedesConfirmar: 'Puedes confirmar hasta',
  invitadoConfirmacion: 'Invitado',
  asistentesAgregados: 'Acompañantes agregados:',
  teEsperamos: '¡Te esperamos!',
  asistiras: '¿Podrás asistir?',
  siAsistire: 'Sí asistiré',
  noAsistira: 'No podré asistir',
  estasSeguro: '¿Estás seguro?',
  fechaConfirmacionCaducada: '¡Ya pasó la fecha límite para confirmar tu asistencia!',
  fechaConfirmacionCaducadaDos: 'Si gustas, puedes comunicarte con los novios.',
   //VENTANA EMERGENTE CONFIRMACION
  confirmAsistenciatitle: '¿Confirmas tu asistencia?',
  opcancelar: 'Cancelar',
  sininvitadostitle: '¿Confirmarás tu asistencia?',
  sininvitadostxt: 'Escribe tu nombre y, si corresponde, el de tus acompañantes para confirmar tu asistencia.',

  // DESPEDIDA
  tituloDespedida: 'Con amor',
  DespedidaNombres: 'Lucia & Junnior',
  // GLASMMY
  textoGlasmmy: 'Created with love by',
  glasmmy: 'GlasmmyDigital'



}
